import navbar from "./componet/navbar.js";
let nav = document.getElementById("navbar");
nav.innerHTML=navbar();
import offers from "./componet/offer.js";
let offer = document.getElementById("offer");
offer.innerHTML=offers();
import search from "./componet/search.js";
let searchs = document.getElementById("search");
searchs.innerHTML=search();
import footer from "./componet/footer.js";
let sfooter = document.getElementById("footer");
sfooter.innerHTML=footer();